-- CG-001 — contacts: enquiries submitted from the Coach Gari website.
-- Extensible on purpose (status, attribution, notified_at) without being a CRM.

create extension if not exists pgcrypto;

create table if not exists public.contacts (
  id             uuid primary key default gen_random_uuid(),
  submission_id  uuid not null unique,          -- idempotency key generated by the browser per form fill
  name           text not null,
  contact        text not null,                 -- email or WhatsApp/phone, as typed by the visitor
  country        text,
  city           text,
  location_raw   text,                          -- the "City and country" field exactly as typed
  interest       text,
  message        text,
  utm_source     text,
  utm_medium     text,
  utm_campaign   text,
  utm_content    text,
  utm_term       text,
  referrer       text,
  landing_page   text,
  first_visit_at timestamptz,
  page           text,                          -- path the form was submitted from
  source         text not null default 'web',
  ip_hash        text,                          -- sha256(salt + ip); used for rate limiting only
  user_agent     text,
  status         text not null default 'new'
                 check (status in ('new', 'contacted', 'qualified', 'closed', 'spam')),
  notified_at    timestamptz,                   -- set when the Resend lead notification succeeded
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists contacts_created_at_idx         on public.contacts (created_at desc);
create index if not exists contacts_ip_hash_created_at_idx on public.contacts (ip_hash, created_at desc);
create index if not exists contacts_contact_created_at_idx on public.contacts (contact, created_at desc);
create index if not exists contacts_status_idx             on public.contacts (status);

create or replace function public.contacts_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end
$$;

drop trigger if exists contacts_set_updated_at on public.contacts;
create trigger contacts_set_updated_at
  before update on public.contacts
  for each row execute function public.contacts_set_updated_at();

-- Locked down: no anon / authenticated access at all.
-- Only the Edge Function (service role, injected by the platform) reads and writes.
alter table public.contacts enable row level security;
revoke all on public.contacts from anon, authenticated;

comment on table public.contacts is 'CG-001 — website enquiries. Extensible; deliberately not a CRM.';
